-- PostgreSQL schema for the question paraphrase/question bank domain.
-- This mirrors the current FastAPI demo schema and keeps string IDs such as
-- Q001, PJ-*, PC-*, DOC-*, DQJ-* so existing seed data can be imported.

CREATE TABLE IF NOT EXISTS questions (
  id VARCHAR(64) PRIMARY KEY,
  stem TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_answer VARCHAR(1) NOT NULL,
  explanation TEXT,
  topic VARCHAR(255),
  difficulty VARCHAR(32),
  language VARCHAR(16) NOT NULL DEFAULT 'vi',
  source_document VARCHAR(255),
  question_type VARCHAR(16) NOT NULL DEFAULT 'ORIGINAL',
  status VARCHAR(16) NOT NULL DEFAULT 'APPROVED',
  parent_question_id VARCHAR(64) REFERENCES questions(id) ON DELETE SET NULL,
  created_by VARCHAR(100),
  reviewed_by VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_questions_correct_answer CHECK (correct_answer IN ('A', 'B', 'C', 'D')),
  CONSTRAINT ck_questions_language CHECK (language IN ('vi', 'en', 'bilingual')),
  CONSTRAINT ck_questions_type CHECK (question_type IN ('ORIGINAL', 'PARAPHRASE')),
  CONSTRAINT ck_questions_status CHECK (status IN ('DRAFT', 'APPROVED', 'REJECTED', 'ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS ix_questions_parent_question_id ON questions(parent_question_id);
CREATE INDEX IF NOT EXISTS ix_questions_status ON questions(status);
CREATE INDEX IF NOT EXISTS ix_questions_topic ON questions(topic);

CREATE TABLE IF NOT EXISTS question_embeddings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id VARCHAR(64) NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  text_type VARCHAR(32) NOT NULL DEFAULT 'stem',
  embedding_model VARCHAR(255) NOT NULL,
  embedding_dimension INTEGER NOT NULL,
  input_text_hash VARCHAR(64) NOT NULL,
  normalized_text TEXT NOT NULL,
  vector DOUBLE PRECISION[] NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_question_embeddings_input UNIQUE (
    question_id,
    text_type,
    embedding_model,
    input_text_hash
  )
);

CREATE INDEX IF NOT EXISTS ix_question_embeddings_question_id ON question_embeddings(question_id);
CREATE INDEX IF NOT EXISTS ix_question_embeddings_model ON question_embeddings(embedding_model);
CREATE INDEX IF NOT EXISTS ix_question_embeddings_hash ON question_embeddings(input_text_hash);

CREATE TABLE IF NOT EXISTS paraphrase_jobs (
  id VARCHAR(64) PRIMARY KEY,
  source_question_id VARCHAR(64) NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
  mode VARCHAR(32) NOT NULL DEFAULT 'STEM_ONLY',
  target_language VARCHAR(16) NOT NULL DEFAULT 'vi',
  requested_count INTEGER NOT NULL DEFAULT 5,
  change_strength VARCHAR(16) NOT NULL DEFAULT 'medium',
  provider VARCHAR(16) NOT NULL DEFAULT 'mock',
  status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
  error_message TEXT,
  created_by VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_paraphrase_jobs_mode CHECK (mode IN ('STEM_ONLY')),
  CONSTRAINT ck_paraphrase_jobs_provider CHECK (provider IN ('mock', 'api', 'local')),
  CONSTRAINT ck_paraphrase_jobs_status CHECK (
    status IN ('CREATED', 'GENERATING', 'GENERATED', 'VALIDATING', 'COMPLETED', 'FAILED')
  ),
  CONSTRAINT ck_paraphrase_jobs_requested_count CHECK (requested_count BETWEEN 1 AND 10)
);

CREATE INDEX IF NOT EXISTS ix_paraphrase_jobs_source_question_id ON paraphrase_jobs(source_question_id);
CREATE INDEX IF NOT EXISTS ix_paraphrase_jobs_status ON paraphrase_jobs(status);

CREATE TABLE IF NOT EXISTS paraphrase_candidates (
  id VARCHAR(64) PRIMARY KEY,
  job_id VARCHAR(64) NOT NULL REFERENCES paraphrase_jobs(id) ON DELETE CASCADE,
  source_question_id VARCHAR(64) NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
  candidate_stem TEXT NOT NULL,
  normalized_candidate_stem TEXT NOT NULL,
  semantic_similarity_to_source DOUBLE PRECISION,
  lexical_difference_from_source DOUBLE PRECISION,
  duplicate_max_similarity DOUBLE PRECISION,
  duplicate_question_id VARCHAR(64),
  duplicate_question_stem_snapshot TEXT,
  label VARCHAR(20),
  warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'GENERATED',
  reviewer_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_paraphrase_candidates_status CHECK (
    status IN ('GENERATED', 'VALIDATED', 'NEED_REVIEW', 'APPROVED', 'REJECTED', 'SAVED')
  ),
  CONSTRAINT ck_paraphrase_candidates_label CHECK (
    label IS NULL OR label IN ('GOOD', 'NEED_REVIEW', 'REJECTED')
  )
);

CREATE INDEX IF NOT EXISTS ix_paraphrase_candidates_job_id ON paraphrase_candidates(job_id);
CREATE INDEX IF NOT EXISTS ix_paraphrase_candidates_source_question_id ON paraphrase_candidates(source_question_id);
CREATE INDEX IF NOT EXISTS ix_paraphrase_candidates_status ON paraphrase_candidates(status);

CREATE TABLE IF NOT EXISTS documents (
  id VARCHAR(64) PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(100),
  status VARCHAR(32) NOT NULL DEFAULT 'READY',
  page_count INTEGER NOT NULL DEFAULT 0,
  chunk_count INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  created_by VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_documents_status CHECK (status IN ('READY', 'OCR_REQUIRED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS ix_documents_status ON documents(status);

CREATE TABLE IF NOT EXISTS document_sections (
  id VARCHAR(64) PRIMARY KEY,
  document_id VARCHAR(64) NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  parent_id VARCHAR(64) REFERENCES document_sections(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  level INTEGER NOT NULL DEFAULT 1,
  order_index INTEGER NOT NULL,
  page_start INTEGER,
  page_end INTEGER,
  path VARCHAR(1000) NOT NULL,
  confidence DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_document_sections_document_id ON document_sections(document_id);
CREATE INDEX IF NOT EXISTS ix_document_sections_order_index ON document_sections(order_index);

CREATE TABLE IF NOT EXISTS document_chunks (
  id VARCHAR(64) PRIMARY KEY,
  document_id VARCHAR(64) NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  section_id VARCHAR(64) REFERENCES document_sections(id) ON DELETE SET NULL,
  parent_chunk_id VARCHAR(64),
  chunk_index INTEGER NOT NULL,
  chunk_type VARCHAR(32) NOT NULL DEFAULT 'generation',
  page_start INTEGER,
  page_end INTEGER,
  section_title VARCHAR(255),
  section_path VARCHAR(1000),
  text TEXT NOT NULL,
  text_hash VARCHAR(64) NOT NULL,
  char_count INTEGER NOT NULL,
  token_count INTEGER NOT NULL DEFAULT 0,
  quality_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
  previous_chunk_id VARCHAR(64),
  next_chunk_id VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_document_chunks_position UNIQUE (document_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id ON document_chunks(document_id);
CREATE INDEX IF NOT EXISTS ix_document_chunks_section_id ON document_chunks(section_id);
CREATE INDEX IF NOT EXISTS ix_document_chunks_chunk_index ON document_chunks(chunk_index);
CREATE INDEX IF NOT EXISTS ix_document_chunks_text_hash ON document_chunks(text_hash);

CREATE TABLE IF NOT EXISTS document_question_jobs (
  id VARCHAR(64) PRIMARY KEY,
  document_id VARCHAR(64) NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  provider VARCHAR(32) NOT NULL DEFAULT 'api',
  model VARCHAR(100),
  prompt_version VARCHAR(64),
  status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
  questions_per_chunk INTEGER NOT NULL DEFAULT 3,
  chunk_count INTEGER NOT NULL DEFAULT 0,
  completed_chunk_count INTEGER NOT NULL DEFAULT 0,
  failed_chunk_count INTEGER NOT NULL DEFAULT 0,
  candidate_count INTEGER NOT NULL DEFAULT 0,
  chunk_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
  llm_call_count INTEGER NOT NULL DEFAULT 0,
  total_prompt_tokens INTEGER NOT NULL DEFAULT 0,
  total_completion_tokens INTEGER NOT NULL DEFAULT 0,
  total_tokens INTEGER NOT NULL DEFAULT 0,
  total_latency_ms INTEGER NOT NULL DEFAULT 0,
  estimated_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  error_message TEXT,
  created_by VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_document_question_jobs_status CHECK (
    status IN ('CREATED', 'GENERATING', 'GENERATED', 'PARTIALLY_COMPLETED', 'FAILED')
  ),
  CONSTRAINT ck_document_question_jobs_qpc CHECK (questions_per_chunk BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS ix_document_question_jobs_document_id ON document_question_jobs(document_id);
CREATE INDEX IF NOT EXISTS ix_document_question_jobs_status ON document_question_jobs(status);

CREATE TABLE IF NOT EXISTS document_knowledge_points (
  id VARCHAR(64) PRIMARY KEY,
  job_id VARCHAR(64) NOT NULL REFERENCES document_question_jobs(id) ON DELETE CASCADE,
  document_id VARCHAR(64) NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  chunk_id VARCHAR(64) NOT NULL REFERENCES document_chunks(id) ON DELETE CASCADE,
  source_key VARCHAR(64),
  statement TEXT NOT NULL,
  knowledge_type VARCHAR(64),
  importance VARCHAR(32),
  source_excerpt TEXT,
  generation_eligible BOOLEAN NOT NULL DEFAULT true,
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_document_knowledge_points_job_id ON document_knowledge_points(job_id);
CREATE INDEX IF NOT EXISTS ix_document_knowledge_points_document_id ON document_knowledge_points(document_id);
CREATE INDEX IF NOT EXISTS ix_document_knowledge_points_chunk_id ON document_knowledge_points(chunk_id);

CREATE TABLE IF NOT EXISTS document_question_candidates (
  id VARCHAR(64) PRIMARY KEY,
  job_id VARCHAR(64) NOT NULL REFERENCES document_question_jobs(id) ON DELETE CASCADE,
  document_id VARCHAR(64) NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  chunk_id VARCHAR(64) NOT NULL REFERENCES document_chunks(id) ON DELETE CASCADE,
  stem TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_answer VARCHAR(1) NOT NULL,
  explanation TEXT,
  topic VARCHAR(255),
  difficulty VARCHAR(32),
  source_excerpt TEXT,
  generation_key VARCHAR(128),
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  quality_score DOUBLE PRECISION,
  llm_validation JSONB,
  label VARCHAR(20),
  warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'GENERATED',
  duplicate_max_similarity DOUBLE PRECISION,
  duplicate_question_id VARCHAR(64),
  duplicate_question_stem_snapshot TEXT,
  reviewer_notes TEXT,
  saved_question_id VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_document_candidates_answer CHECK (correct_answer IN ('A', 'B', 'C', 'D')),
  CONSTRAINT ck_document_candidates_status CHECK (
    status IN ('GENERATED', 'VALIDATED', 'NEED_REVIEW', 'APPROVED', 'REJECTED', 'SAVED')
  ),
  CONSTRAINT ck_document_candidates_label CHECK (
    label IS NULL OR label IN ('GOOD', 'NEED_REVIEW', 'REJECTED')
  )
);

CREATE INDEX IF NOT EXISTS ix_document_candidates_job_id ON document_question_candidates(job_id);
CREATE INDEX IF NOT EXISTS ix_document_candidates_document_id ON document_question_candidates(document_id);
CREATE INDEX IF NOT EXISTS ix_document_candidates_chunk_id ON document_question_candidates(chunk_id);
CREATE INDEX IF NOT EXISTS ix_document_candidates_status ON document_question_candidates(status);
CREATE INDEX IF NOT EXISTS ix_document_candidates_generation_key ON document_question_candidates(generation_key);
CREATE INDEX IF NOT EXISTS ix_document_candidates_saved_question_id ON document_question_candidates(saved_question_id);

CREATE TABLE IF NOT EXISTS exams (
  id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  created_by VARCHAR(100) NOT NULL DEFAULT 'demo-user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exam_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id VARCHAR(64) NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  question_id VARCHAR(64) NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_exam_questions_exam_question UNIQUE (exam_id, question_id)
);

CREATE INDEX IF NOT EXISTS ix_exam_questions_exam_id ON exam_questions(exam_id);
CREATE INDEX IF NOT EXISTS ix_exam_questions_question_id ON exam_questions(question_id);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type VARCHAR(64) NOT NULL,
  entity_id VARCHAR(64) NOT NULL,
  action VARCHAR(100) NOT NULL,
  actor VARCHAR(100) NOT NULL DEFAULT 'system',
  before_json JSONB,
  after_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_entity_type ON audit_logs(entity_type);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity_id ON audit_logs(entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_action ON audit_logs(action);
